#!/usr/bin/env python
"""
YouTube Cookie Exporter using Playwright.
Opens a browser window for you to log into YouTube, then exports cookies automatically.
"""
import json
from pathlib import Path
from playwright.sync_api import sync_playwright

CACHE_DIR = Path(r"c:\Users\saziz\video-dj-playlist\cache")
COOKIES_FILE = CACHE_DIR / "youtube_cookies.txt"
STATE_FILE = CACHE_DIR / "youtube_state.json"


def export_cookies():
    """Open browser, let user log in, and export cookies."""
    print("=" * 60)
    print("YouTube Login Helper for AI DJ Studio")
    print("=" * 60)
    print()
    print("A browser window will open. Please:")
    print("1. Log into your Google account if prompted")
    print("2. Wait for YouTube to fully load")
    print("3. Close the browser window when done")
    print()
    print("Starting browser...")
    
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    
    with sync_playwright() as p:
        # Use persistent context to save state
        browser = p.chromium.launch(headless=False)
        
        # Load existing state if available
        context_options = {"viewport": {"width": 1280, "height": 800}}
        if STATE_FILE.exists():
            try:
                context_options["storage_state"] = str(STATE_FILE)
                print("Loaded existing session state...")
            except:
                pass
        
        context = browser.new_context(**context_options)
        page = context.new_page()
        
        print("Opening YouTube...")
        page.goto("https://www.youtube.com")
        
        print()
        print("-" * 60)
        print("Please log into YouTube if needed, then close the browser.")
        print("-" * 60)
        
        # Wait for user to close the browser
        try:
            page.wait_for_event("close", timeout=300000)  # 5 minute timeout
        except:
            pass
        
        # Save state for next time
        try:
            context.storage_state(path=str(STATE_FILE))
            print("\nSession state saved for future use.")
        except:
            pass
        
        # Get all cookies
        cookies = context.cookies()
        
        # Filter for YouTube cookies
        yt_cookies = [c for c in cookies if "youtube" in c.get("domain", "").lower()]
        
        print(f"\nFound {len(yt_cookies)} YouTube cookies")
        
        # Check for login cookies
        login_cookie_names = ["SID", "SSID", "HSID", "LOGIN_INFO", "__Secure-1PSID"]
        has_login = any(c["name"] in login_cookie_names for c in yt_cookies)
        
        if has_login:
            print("[SUCCESS] Login cookies detected!")
        else:
            print("[WARNING] No login cookies found - you may not be logged in")
        
        # Export in Netscape format
        with open(COOKIES_FILE, "w") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by AI DJ Studio\n\n")
            
            for cookie in yt_cookies:
                domain = cookie.get("domain", "")
                if not domain.startswith("."):
                    domain = "." + domain
                
                flag = "TRUE" if domain.startswith(".") else "FALSE"
                path = cookie.get("path", "/")
                secure = "TRUE" if cookie.get("secure", False) else "FALSE"
                expires = str(int(cookie.get("expires", 0)))
                name = cookie.get("name", "")
                value = cookie.get("value", "")
                
                f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")
        
        print(f"\nCookies saved to: {COOKIES_FILE}")
        
        context.close()
        browser.close()
    
    # Verify the file
    if COOKIES_FILE.exists():
        lines = COOKIES_FILE.read_text().split("\n")
        cookie_lines = [l for l in lines if l and not l.startswith("#")]
        print(f"\nExported {len(cookie_lines)} cookies")
        
        # List important cookies
        important = ["SID", "SSID", "LOGIN_INFO", "__Secure-1PSID", "VISITOR_INFO1_LIVE"]
        found = []
        for line in cookie_lines:
            parts = line.split("\t")
            if len(parts) >= 6 and parts[5] in important:
                found.append(parts[5])
        
        if found:
            print(f"Important cookies found: {', '.join(found)}")
        
        return has_login
    
    return False


if __name__ == "__main__":
    success = export_cookies()
    if success:
        print("\n" + "=" * 60)
        print("SUCCESS! You can now use AI DJ Studio.")
        print("=" * 60)
    else:
        print("\n" + "=" * 60)
        print("Please make sure you log into YouTube with your Google account")
        print("and run this script again.")
        print("=" * 60)
